### ISSUE TITLE
libx264 optional codec support?

### ISSUE THREAD

**Issue by adammoisa** [limistah/ffmpeg-webworker#1]
This is a really great and easy to use lib to work with ffmpeg and workers - thank you!

Is there plan to allow users to specify or manually add which codec's they'd like to support? For example, libx264 isn't bundled with this, how would I go about adding it so it can be used with your lib?

**Comment by limistah** [comment]
Thanks for the compliment. :+1: 

Actually, there is a possibility of this, I will include as an option in the next update.

**Comment by vasanthudhaya** [comment]
When will you give the next update and the libx264 codec support. @limistah

**Comment by limistah** [comment]
> When will you give the next update and the libx264 codec support. @limistah

@vasanthudhaya 
I have been trying to get it completed following this: http://bgrins.github.io/videoconverter.js/#build,
but it has not always been successful.

I am seeking other option of using the pre-built all codecs, my fear is that it might get too heavy.

**Comment by limistah** [comment]
@adammoisa 

I was unable to get individual codecs, but the good news here is that, I have been able to work with https://github.com/bgrins/videoconverter.js/tree/master/build which has a build for all of the codecs.

Kindly see the [demo page](https://limistah.github.io/ffmpeg-webworker/) for supported codecs.

And ensure to pass the codec to use when issuing a command.
